#!/usr/bin/env bash
# Markdown tracker adapter: one file per ticket, <project-root>/<tickets_dir>/<KEY>.md.
#
# File shape (see templates/ticket.template.md):
#   ---                      front matter: key, title, status (a canonical state), assignee
#   ...
#   ---
#   # KEY: title             the human zone — prose, numbered acceptance criteria
#   ...
#   <!-- adlc:machine-zone ... -->
#   ```adlc                  the machine zone: exactly one fenced block, nothing after it
#   ...
#   ```
# Called by adlc-tracker.sh, which validates the arguments and exports ADLC_* settings.
set -euo pipefail

MARKER='<!-- adlc:machine-zone — generated by /refine; never edit by hand. Re-run /refine to change it. -->'
ACTION="$1"
KEY="$2"
shift 2
DIR="${ADLC_TICKETS_DIR:-docs/tickets}"
[[ "$DIR" == /* ]] || DIR="$ADLC_PROJECT_ROOT/$DIR"
FILE="$DIR/$KEY.md"
[[ -f "$FILE" ]] || { echo "markdown tracker: no ticket file $FILE" >&2; exit 3; }

fm_get() {
  awk -v k="$1" 'NR == 1 && $0 != "---" { exit } NR > 1 && $0 == "---" { exit }
    NR > 1 && index($0, k ": ") == 1 { v = substr($0, length(k) + 3); gsub(/^"|"$/, "", v); print v; exit }' "$FILE"
}

fm_set() {
  local k="$1" v="$2" tmp
  tmp="$(mktemp)"
  awk -v k="$k" -v v="$v" '
    NR == 1 { if ($0 != "---") { bad = 1 } ; print; next }
    !done && !bad && $0 == "---" { if (!set) print k ": \"" v "\""; done = 1; print; next }
    !done && !bad && index($0, k ": ") == 1 { print k ": \"" v "\""; set = 1; next }
    { print }
    END { if (bad) exit 4 }
  ' "$FILE" >"$tmp" || { rm -f "$tmp"; echo "markdown tracker: $FILE has no front matter" >&2; exit 4; }
  cat "$tmp" >"$FILE"
  rm -f "$tmp"
}

# human_zone  -> the file without the machine-zone marker and block
human_zone() {
  awk -v m="$MARKER" '$0 == m { exit } /^```adlc[ \t]*$/ { exit } { print }' "$FILE"
}

machine_zone() {
  awk -v m="$MARKER" 'f { print; next } $0 == m || /^```adlc[ \t]*$/ { f = 1; print }' "$FILE"
}

# insert_before_machine_zone <md-file>
insert_before_machine_zone() {
  local tmp
  tmp="$(mktemp)"
  {
    human_zone | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
    echo
    cat "$1"
    echo
    machine_zone
  } >"$tmp"
  cat "$tmp" >"$FILE"
  rm -f "$tmp"
}

case "$ACTION" in
  fetch)
    human_zone
    ;;
  status)
    s="$(fm_get status)"
    case " draft in-refinement ready-for-agent in-progress in-review done " in
      *" $s "*) echo "$s" ;;
      *) echo "other:$s" ;;
    esac
    ;;
  transition)
    fm_set status "$1"
    echo "markdown tracker: $KEY -> $1"
    ;;
  claim)
    who="${ADLC_USER:-$(git -C "$ADLC_PROJECT_ROOT" config user.name 2>/dev/null || id -un)}"
    fm_set assignee "$who"
    echo "markdown tracker: $KEY assigned to $who"
    ;;
  read-block)
    out="$1"
    n="$(grep -cE '^```adlc[ \t]*$' "$FILE" || true)"
    [[ "$n" -gt 0 ]] || { echo "markdown tracker: $KEY has no machine block" >&2; exit 3; }
    [[ "$n" -eq 1 ]] || { echo "markdown tracker: $KEY has $n machine blocks; exactly one is allowed" >&2; exit 4; }
    awk '/^```adlc[ \t]*$/ { f = 1 } f { print } f && /^```[ \t]*$/ { exit }' "$FILE" >"$out"
    ;;
  write-block)
    block="$1"
    tmp="$(mktemp)"
    {
      human_zone | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
      echo
      echo "$MARKER"
      awk '/^```adlc[ \t]*$/ { f = 1 } f { print } f && /^```[ \t]*$/ { exit }' "$block"
    } >"$tmp"
    cat "$tmp" >"$FILE"
    rm -f "$tmp"
    echo "markdown tracker: machine block written to $FILE"
    ;;
  append)
    insert_before_machine_zone "$1"
    echo "markdown tracker: appended to the human zone of $FILE"
    ;;
  comment)
    note="$(mktemp)"
    {
      echo "### Comment — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      echo
      cat "$1"
    } >"$note"
    insert_before_machine_zone "$note"
    rm -f "$note"
    echo "markdown tracker: comment added to $FILE"
    ;;
  *)
    echo "markdown tracker: unknown action $ACTION" >&2
    exit 2
    ;;
esac
